### ISSUE TITLE
Remove modula2 patch (included upstream)

### ISSUE THREAD

**Issue by nsavch** [Wojtek242-RPM/rpm-emacs-git#1]
Hi,

The modula2 mode was patched upstream: https://github.com/emacs-mirror/emacs/commit/0b48e2d258cb3c0ad5d12c5b4aaf9b4b69101763 

Apparently that's the reason why the build is failing on COPR atm. Could you try to remove the `emacs-modula2.patch` from this build please? Thanks.

**Comment by mavit** [comment]
I’ve made a few other upstream changes around desktop integration recently which I expect will break the RPM build too.  There are new .desktop files to be packaged, and `emacs.appdata.xml` was renamed to `emacs.metainfo.xml`.

**Comment by Wojtek242** [comment]
https://copr.fedorainfracloud.org/coprs/robot/emacs-git/build/2314684/

F34 and rawhide builds fixed :). Thanks for the pointers and the motivational kick to get it fixed. Now I can enjoy the new build myself as well.

F33 is failing for some other reason though. I'll have a look tomorrow.
