### ISSUE TITLE
emacs: could not load dump file

### ISSUE THREAD

**Issue by Jackson-soft** [Wojtek242-RPM/rpm-emacs-git#3]
➜ ~ emacs -nw
desired fingerprint: 981c805707b18456c1b805ec4ae67f65438aca59cde9cd37cc2e08d6fcc5e2a3
found fingerprint: ba3f2c30631f45795dbbd134209c89de0a913eb1fac7d69f84ca401d56474fbc
emacs: could not load dump file "/usr/bin/emacs-29.0.50.pdmp": not built for this Emacs executable

**Comment by yunusemrecan** [comment]
as Jan 4,2022 
I got this message 

desired fingerprint: f35327cfaaacc2a4ab5aa08cedc7826593535122c4245d10ced654b8a215c07d
found fingerprint: 15c8ef73728a81345d61fcda0eb66f5dc6cf5125853b751394f9206be39b9fe1
emacs: could not load dump file "/usr/bin/emacs-29.0.50.pdmp": not built for this Emacs executable

**Comment by Wojtek242** [comment]
Hi, this is hopefully fixed now with the latest version. Give it a go and let me know if it's not working.

I will close this issue, but please reopen if you're still having this issue.
